import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * The runner configuration that makes the emitted tests actually run.
 *
 * `pin` wrote a suite and left the reader to work out why nothing executed it.
 * A field report from a real install hit exactly that: it wrote a `vitest`
 * config by hand after discovering that a bare `vitest run` collected 153 test
 * files, most of them belonging to other packages. The cache no longer sits in
 * the project so that particular collision is gone, but the gap it exposed is
 * real — a suite nobody runs cannot fail when an upgrade removes something,
 * which is the entire reason it exists.
 *
 * **Nothing here overwrites anything.** A project's own `vitest.config.ts` is
 * load-bearing for its whole suite, and a `test` script is how its CI runs.
 * Both are left exactly as they are; this adds a separate config under a name
 * of its own and a script beside the ones already there.
 */

/** A name of our own, so it cannot collide with the project's config. */
export const CONTRACT_CONFIG = "vitest.contract.config.ts";

/** The script that runs only the contract tests. */
export const CONTRACT_SCRIPT = "test:contract";

export type RunnerSetup = {
  /** The config file, when one was written. Null when one was already there. */
  config: string | null;
  /** True when the script was added. False when it existed, or could not be added. */
  script: boolean;
  /** What stopped us, when something did. */
  notes: string[];
};

function configFor(testDir: string, generator: string, at: string): string {
  const glob = `${testDir.replace(/\\/g, "/").replace(/\/+$/, "")}/**/*.contract.test.ts`;
  return [
    `// Generated by ${generator} on ${at}.`,
    `//`,
    `// Runs only the contract tests in \`${testDir}\`, so this never competes with`,
    `// the project's own vitest config or collects anybody else's suite.`,
    `//`,
    `//     npm run ${CONTRACT_SCRIPT}`,
    `//`,
    `// Safe to edit. Nothing regenerates this file once it exists.`,
    ``,
    `export default {`,
    `  test: {`,
    `    include: [${JSON.stringify(glob)}],`,
    `  },`,
    `};`,
    ``,
  ].join("\n");
}

/**
 * Write the config and add the script, skipping whatever is already there.
 *
 * The manifest is rewritten with `JSON.parse`/`JSON.stringify`, which drops
 * comment-like formatting a person may have had — so it is only touched when
 * the script is genuinely absent, and never to change one that exists.
 */
export function setupRunner(options: {
  root: string;
  testDir: string;
  generator: string;
  generatedAt?: string;
}): RunnerSetup {
  const { root, testDir, generator } = options;
  const at = options.generatedAt ?? new Date().toISOString();
  const notes: string[] = [];

  let config: string | null = null;
  const configPath = join(root, CONTRACT_CONFIG);
  if (existsSync(configPath)) {
    notes.push(`${CONTRACT_CONFIG} already exists and was left alone`);
  } else {
    try {
      writeFileSync(configPath, configFor(testDir, generator, at), "utf8");
      config = CONTRACT_CONFIG;
    } catch (error) {
      notes.push(`could not write ${CONTRACT_CONFIG}: ${message(error)}`);
    }
  }

  let script = false;
  const manifestPath = join(root, "package.json");
  try {
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Record<string, unknown>;
    const scripts = (manifest["scripts"] ?? {}) as Record<string, unknown>;
    if (typeof scripts[CONTRACT_SCRIPT] === "string") {
      notes.push(`the \`${CONTRACT_SCRIPT}\` script already exists and was left alone`);
    } else {
      scripts[CONTRACT_SCRIPT] = `vitest run --config ${CONTRACT_CONFIG}`;
      manifest["scripts"] = scripts;
      writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
      script = true;
    }
  } catch (error) {
    // Never fatal. The tests are already written and are the point; a script is
    // a convenience, and a manifest we could not parse is one somebody is in
    // the middle of editing.
    notes.push(`could not add the \`${CONTRACT_SCRIPT}\` script: ${message(error)}`);
  }

  return { config, script, notes };
}

function message(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
