import { describe, expect, test } from "vitest";
import type { Assertion } from "./taxonomy.js";
import { renderVitest, testFileName } from "./vitest.js";

function render(assertions: Assertion[], subpath = "./pack"): string {
  return renderVitest({
    package: "@example/tools",
    subpath,
    assertions,
    version: "1.4.0",
    generator: "stantal 0.1.0",
    generatedAt: "2026-01-01T00:00:00.000Z",
  });
}

const present: Assertion = { kind: "tool_present", subpath: "./pack", tool: "build", why: "removed in 1.5.0" };

describe("the generated file is honest about itself", () => {
  test("says where it came from and how to regenerate it", () => {
    const out = render([present]);
    expect(out).toContain("Generated by stantal 0.1.0 on 2026-01-01T00:00:00.000Z.");
    expect(out).toContain("Taken from @example/tools@1.4.0");
    expect(out).toContain("Regenerate:  npx stantal pin @example/tools --surface ./pack");
  });

  test("says a failure is not automatically the package's fault", () => {
    // A generated suite that reads as an accusation gets deleted. What a
    // failure actually means is that the contract moved and the code written
    // against it needs looking at.
    expect(render([present])).toContain("not automatically a bug");
  });

  test("every test carries the reason it exists", () => {
    const out = render([present]);
    expect(out).toContain("  // removed in 1.5.0");
  });

  test("imports only the helpers it uses", () => {
    expect(render([present])).toContain(`import { findTool, loadContract, type Contract } from "stantal/testkit";`);

    const withParam: Assertion = { kind: "param_optional", subpath: "./pack", tool: "build", param: "target", why: "" };
    expect(render([withParam])).toContain(`import { findParam, loadContract, type Contract }`);

    const documented: Assertion = { kind: "param_documented", subpath: "./pack", tool: "build", param: "target", why: "" };
    expect(render([documented])).toContain(`import { documentsParam, loadContract, type Contract }`);
  });
});

describe("text from a package is escaped, never interpolated raw", () => {
  test("a description containing quotes, newlines and backslashes survives", () => {
    // Descriptions are arbitrary text from someone else's package. Pasted in
    // unescaped, a stray quote produces a file that does not parse, and the
    // whole suite is lost rather than one test.
    const nasty = 'He said "pass `target`" \\ then\na new line — and a backtick ` too';
    const a: Assertion = {
      kind: "description_includes",
      subpath: "./pack",
      tool: "build",
      expected: nasty,
      why: "deleted",
    };
    const out = render([a]);
    expect(out).toContain(JSON.stringify(nasty));
    expect(out).not.toContain("\n  He said");
  });

  test("a tool name with characters that are special in a regex is quoted", () => {
    const a: Assertion = { kind: "tool_present", subpath: "./pack", tool: 'odd"name', why: "" };
    expect(render([a])).toContain('findTool(contract, "odd\\"name")');
  });
});

describe("assertion bodies", () => {
  const cases: Array<[string, Assertion, string]> = [
    ["present tool", present, "expect(findTool(contract, \"build\")).not.toBeNull();"],
    [
      "optional param",
      { kind: "param_optional", subpath: "./pack", tool: "build", param: "target", why: "" },
      'expect(findParam(contract, "build", "target")?.required).toBe(false);',
    ],
    [
      "required param",
      { kind: "param_required", subpath: "./pack", tool: "build", param: "out", why: "" },
      'expect(findParam(contract, "build", "out")?.required).toBe(true);',
    ],
    [
      "param type",
      { kind: "param_type", subpath: "./pack", tool: "build", param: "n", expected: "number", why: "" },
      'expect(findParam(contract, "build", "n")?.type).toBe("number");',
    ],
    [
      "documented param",
      { kind: "param_documented", subpath: "./pack", tool: "build", param: "target", why: "" },
      'expect(documentsParam(contract, "build", "target")).toBe(true);',
    ],
  ];

  for (const [name, assertion, expected] of cases) {
    test(name, () => {
      expect(render([assertion])).toContain(expected);
    });
  }

  test("an enum assertion checks containment, not equality", () => {
    // The package is allowed to add values. Only losing one breaks a caller,
    // so asserting the exact set would fail on a harmless widening.
    const a: Assertion = {
      kind: "enum_includes",
      subpath: "./pack",
      tool: "build",
      param: "mode",
      expected: ["fast", "safe"],
      why: "",
    };
    const out = render([a]);
    expect(out).toContain('expect.arrayContaining(["fast","safe"])');
  });
});

describe("grouping and the empty case", () => {
  test("one describe block per tool", () => {
    const out = render([
      present,
      { kind: "param_present", subpath: "./pack", tool: "build", param: "target", why: "" },
      { kind: "tool_present", subpath: "./pack", tool: "deploy", why: "" },
    ]);
    expect(out.match(/^describe\(/gm)).toHaveLength(2);
    expect(out).toContain('describe("@example/tools ./pack · build"');
    expect(out).toContain('describe("@example/tools ./pack · deploy"');
  });

  test("an empty result says so instead of looking like coverage", () => {
    // A file with no assertions in it reads as "checked, all fine". It is not,
    // and the difference is the whole point of every other invariant here.
    const out = render([]);
    expect(out).toContain("Nothing in this contract could be pinned");
    expect(out).toContain("still exposes a readable contract");
  });
});

describe("file names", () => {
  test("are unique per door and safe on every filesystem", () => {
    expect(testFileName("@example/tools", ".")).toBe("example-tools.root.contract.test.ts");
    expect(testFileName("@example/tools", "./ai-sdk")).toBe("example-tools.ai-sdk.contract.test.ts");
    expect(testFileName("example", "bin:my-server")).toBe("example.bin-my-server.contract.test.ts");
  });

  test("two doors of one package never collide", () => {
    expect(testFileName("p", "./a")).not.toBe(testFileName("p", "./b"));
  });
});
