import type { Assertion } from "./taxonomy.js";

/**
 * Rendering assertions as a Vitest file.
 *
 * Three properties the generated file has to have, all of them about whether a
 * stranger trusts it enough to keep it:
 *
 * 1. **It is readable.** Plain `expect` calls over plain data, no custom
 *    matchers and no cleverness. Someone who has never heard of this tool has
 *    to be able to read a failure and decide what it means without looking
 *    anything up.
 * 2. **Every test says why it exists.** A generated assertion with no reason
 *    attached is deleted the first time it fails, and it takes the rest of the
 *    file with it.
 * 3. **It never calls out.** The contract is read statically out of
 *    `node_modules`. No network, and the package under test is never executed.
 */

export type RenderOptions = {
  package: string;
  subpath: string;
  assertions: readonly Assertion[];
  /** The version the assertions were taken from, named in the header. */
  version?: string;
  /** Emitter identity, so a regenerated file is traceable to a release. */
  generator?: string;
  generatedAt?: string;
  /** How the reader regenerates this file. */
  command?: string;
};

const q = (value: string): string => JSON.stringify(value);

/** A filename that is stable, unique per door, and safe on every filesystem. */
export function testFileName(pkg: string, subpath: string): string {
  const slug = (s: string) => s.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "").toLowerCase();
  const door = subpath === "." ? "root" : slug(subpath);
  return `${slug(pkg)}.${door}.contract.test.ts`;
}

function title(a: Assertion): string {
  switch (a.kind) {
    case "tool_present":
      return `still offers ${a.tool}`;
    case "param_present":
      return `still takes ${a.param}`;
    case "param_optional":
      return `still lets callers omit ${a.param}`;
    case "param_required":
      return `still requires ${a.param}`;
    case "param_type":
      return `still types ${a.param} as ${String(a.expected)}`;
    case "enum_includes":
      return `still admits every value this project passes for ${a.param}`;
    case "description_includes":
      return `still carries the sentence its callers were written against`;
    case "param_documented":
      return `still explains when to pass ${a.param}`;
  }
}

function body(a: Assertion): string[] {
  const tool = q(a.tool);
  const param = a.param === undefined ? null : q(a.param);
  switch (a.kind) {
    case "tool_present":
      return [`expect(findTool(contract, ${tool})).not.toBeNull();`];
    case "param_present":
      return [`expect(findParam(contract, ${tool}, ${param})).not.toBeNull();`];
    case "param_optional":
      return [`expect(findParam(contract, ${tool}, ${param})?.required).toBe(false);`];
    case "param_required":
      return [`expect(findParam(contract, ${tool}, ${param})?.required).toBe(true);`];
    case "param_type":
      return [`expect(findParam(contract, ${tool}, ${param})?.type).toBe(${q(String(a.expected))});`];
    case "enum_includes": {
      const values = Array.isArray(a.expected) ? a.expected : [];
      return [
        `expect(findParam(contract, ${tool}, ${param})?.constraints.enum).toEqual(`,
        `  expect.arrayContaining(${JSON.stringify(values)}),`,
        `);`,
      ];
    }
    case "description_includes":
      return [
        `expect(findTool(contract, ${tool})?.description ?? "").toContain(`,
        `  ${q(String(a.expected))},`,
        `);`,
      ];
    case "param_documented":
      return [`expect(documentsParam(contract, ${tool}, ${param})).toBe(true);`];
  }
}

/** Which testkit helpers this file actually uses, so the import stays honest. */
function imports(assertions: readonly Assertion[]): string[] {
  const used = new Set<string>(["loadContract"]);
  for (const a of assertions) {
    if (a.kind === "param_documented") used.add("documentsParam");
    else if (a.kind === "tool_present" || a.kind === "description_includes") used.add("findTool");
    else used.add("findParam");
  }
  return [...used].sort();
}

export function renderVitest(options: RenderOptions): string {
  const { package: pkg, subpath, assertions } = options;
  const generator = options.generator ?? "stantal";
  const at = options.generatedAt ?? new Date().toISOString();
  const command = options.command ?? `npx stantal pin ${pkg}${subpath === "." ? "" : ` --surface ${subpath}`}`;
  const version = options.version;

  const lines: string[] = [];
  lines.push(`// Generated by ${generator} on ${at}.`);
  lines.push(`//`);
  lines.push(`// Pins the parts of ${pkg}'s tool contract that this project relies on`);
  lines.push(`// through the ${subpath === "." ? "package root" : `"${subpath}"`} import.`);
  if (version !== undefined) lines.push(`// Taken from ${pkg}@${version}, which is what these assertions describe.`);
  lines.push(`//`);
  lines.push(`// A failure here is not automatically a bug in ${pkg}. It means the contract a`);
  lines.push(`// model reads has moved, and the code written against it needs a look before`);
  lines.push(`// the upgrade lands.`);
  lines.push(`//`);
  lines.push(`// The contract is read statically out of node_modules. Nothing here reaches the`);
  lines.push(`// network, and ${pkg} is never executed.`);
  lines.push(`//`);
  lines.push(`// Regenerate:  ${command}`);
  lines.push(``);
  lines.push(`import { beforeAll, describe, expect, it } from "vitest";`);
  lines.push(`import { ${imports(assertions).join(", ")}, type Contract } from "stantal/testkit";`);
  lines.push(``);
  lines.push(`let contract: Contract;`);
  lines.push(``);
  lines.push(`beforeAll(async () => {`);
  lines.push(`  contract = await loadContract({ package: ${q(pkg)}, subpath: ${q(subpath)} });`);
  lines.push(`});`);
  lines.push(``);

  if (assertions.length === 0) {
    // An empty file is worse than none: it looks like coverage. Say plainly
    // that nothing was pinned, and leave a test that proves the door still
    // opens, which is the one claim that survives having read no descriptors.
    lines.push(`// Nothing in this contract could be pinned. Either no findings earned a test,`);
    lines.push(`// or too little of the contract could be read to assert anything about it.`);
    lines.push(`describe(${q(`${pkg} ${subpath}`)}, () => {`);
    lines.push(`  it("still exposes a readable contract", () => {`);
    lines.push(`    expect(contract.tools.length).toBeGreaterThan(0);`);
    lines.push(`  });`);
    lines.push(`});`);
    lines.push(``);
    return lines.join("\n");
  }

  const byTool = new Map<string, Assertion[]>();
  for (const a of assertions) {
    const list = byTool.get(a.tool);
    if (list === undefined) byTool.set(a.tool, [a]);
    else list.push(a);
  }

  for (const [tool, group] of byTool) {
    lines.push(`describe(${q(`${pkg} ${subpath} · ${tool}`)}, () => {`);
    let first = true;
    for (const a of group) {
      if (!first) lines.push(``);
      first = false;
      lines.push(`  // ${a.why}`);
      lines.push(`  it(${q(title(a))}, () => {`);
      for (const line of body(a)) lines.push(`    ${line}`);
      lines.push(`  });`);
    }
    lines.push(`});`);
    lines.push(``);
  }

  return lines.join("\n");
}
